### Supply Network Design

#### Problem Description

In this problem, we have six end customers, each with a known demand for a product.  Customer demand can be satisfied from a set of six depots, or directly from a set of two factories.  Each depot can support a maximum volume of product moving through it, and each factory can produce a maximum amount of product.  There are known costs associated with transporting the product, from a factory to a depot, from a depot to a customer, or from a factory directly to a customer. This extension provides the opportunity to choose which four of the six possible depots to open.  It also provides an option of expanding capacity at one specific depot.

Our supply network has two factories, in Liverpool and Brighton, that produce a product.  Each has a maximum production capacity:

| Factory | Supply (tons) |
| --- | --- |
| Liverpool | 150,000 |
| Brighton |  200,000 |

The product can be shipped from a factory to a set of six depots.  Each depot has a maximum throughput.  Depots don't produce or consume the product; they simply pass the product through to customers.

| Depot | Throughput (tons) |
| --- | --- |
| Newcastle | 70,000 |
| Birmingham | 50,000 |
| London | 100,000 |
| Exeter | 40,000 |
| Bristol | 30,000 |
| Northampton | 25,000 |

We can actually only choose four of the six depots to open.  Opening a depot has a cost:

| Depot | Cost to open |
| --- | --- |
| Newcastle | 10,000 |
| Exeter | 5,000 |
| Bristol | 12,000 |
| Northampton | 4,000 |

(Note that the description in the book talks about the cost of opening Bristol or Northampton, and the savings from closing Newcastle or Exeter, but these are simply different ways of phrasing the same choice).

We also have the option of expanding the capacity at Birmingham by 20,000 tons, for a cost of \$3000.

Our network has six customers, each with a given demand.

| Customer | Demand (tons) |
| --- | --- |
| C1 | 50,000 |
| C2 | 10,000 |
| C3 | 40,000 |
| C4 | 35,000 |
| C5 | 60,000 |
| C6 | 20,000 |

- Shipping costs are given in the following table (in dollars per ton).  Columns are source cities and rows are destination cities.  Thus, for example, it costs $1 per ton to ship the product from Liverpool to London.  
- A '-' in the table indicates that that combination is not possible, so for example it is not possible to ship from the factory in Brighton to the depot in Newcastle.



|Depots\To | Liverpool | Brighton | Newcastle | Birmingham | London | Exeter | Briston | Northhampton |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Newcastle   | 0.5 |   - | --- | --- | --- | --- | --- | --- |
| Birmingham  | 0.5 | 0.3 | --- | --- | --- | --- | --- | --- |
| London      | 1.0 | 0.5 | --- | --- | --- | --- | --- | --- |
| Exeter      | 0.2 | 0.2 | --- | --- | --- | --- | --- | --- |
| Bristol     | 0.6 | 0.4 | --- | --- | --- | --- | --- | --- |
| Northampton | 0.4 | 0.3 | --- | --- | --- | --- | --- | --- |

-

| Customers\To | Liverpool | Brighton | Newcastle | Birmingham | London | Exeter | Briston | Northhampton |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| C1 | 1.0 | 2.0 |   - | 1.0 |   - |   - | 1.2 |   - |
| C2 |   - |   - | 1.5 | 0.5 | 1.5 |   - | 0.6 | 0.4 |
| C3 | 1.5 |   - | 0.5 | 0.5 | 2.0 | 0.2 | 0.5 |   - |
| C4 | 2.0 |   - | 1.5 | 1.0 |   - | 1.5 |   - | 0.5 |
| C5 |   - |   - |   - | 0.5 | 0.5 | 0.5 | 0.3 | 0.6 |
| C6 | 1.0 |   - | 1.0 |   - | 1.5 | 1.5 | 0.8 | 0.9 |

The questions to be answered: (i) Which four depots should be opened? (ii) Should Birmingham be expanded? (iii) Which depots should be used to satisfy customer demand?

---
#### Model Formulation

#### Sets and Indices

$f \in \text{Factories}=\{\text{Liverpool}, \text{Brighton}\}$

$d \in \text{Depots}=\{\text{Newcastle}, \text{Birmingham}, \text{London}, \text{Exeter}, \text{Bristol}, \text{Northampton}\}$

$c \in \text{Customers}=\{\text{C1}, \text{C2}, \text{C3}, \text{C4}, \text{C5}, \text{C6}\}$

$\text{Cities} = \text{Factories} \cup \text{Depots} \cup \text{Customers}$

#### Parameters

$\text{cost}_{s,t} \in \mathbb{R}^+$: Cost of shipping one ton from source $s$ to destination $t$.

$\text{supply}_f \in \mathbb{R}^+$: Maximum possible supply from factory $f$ (in tons).

$\text{through}_d \in \mathbb{R}^+$: Maximum possible flow through depot $d$ (in tons).

$\text{demand}_c \in \mathbb{R}^+$: Demand for goods at customer $c$ (in tons).

$\text{opencost}_d \in \mathbb{R}^+$: Cost of opening depot $d$ (in dollars).

#### Decision Variables

$\text{flow}_{s,t} \in \mathbb{N}^+$: Quantity of goods (in tons) that is shipped from source $s$ to destionation $t$.

$\text{open}_{d} \in [0,1]$: Is depot $d$ open?

$\text{expand} \in [0,1]$: Should Birmingham be expanded?


#### Objective Function

- **Cost**: Minimize total shipping costs plus costs of opening depots.

\begin{equation}
\text{Minimize} \quad Z = \sum_{(s,t) \in \text{Cities} \times \text{Cities}}{\text{cost}_{s,t}*\text{flow}_{s,t}} +
                          \sum_{{d} \in \text{Depots}}{\text{opencost}_d*\text{open}_d} +
                          3000 * \text{expand}
\end{equation}

#### Constraints

- **Factory output**: Flow of goods from a factory must respect maximum capacity.

\begin{equation}
\sum_{t \in \text{Cities}}{\text{flow}_{f,t}} \leq \text{supply}_{f} \quad \forall f \in \text{Factories}
\end{equation}

- **Customer demand**: Flow of goods must meet customer demand.

\begin{equation}
\sum_{s \in \text{Cities}}{\text{flow}_{s,c}} = \text{demand}_{c} \quad \forall c \in \text{Customers}
\end{equation}

- **Depot flow**: Flow into a depot equals flow out of the depot.

\begin{equation}
\sum_{s \in \text{Cities}}{\text{flow}_{s,d}} =
\sum_{t \in \text{Cities}}{\text{flow}_{d,t}}
\quad \forall d \in \text{Depots}
\end{equation}

- **Depot capacity (all but Birmingham)**: Flow into a depot must respect depot capacity, and is only allowed if the depot is open.

\begin{equation}
\sum_{s \in \text{Cities}}{\text{flow}_{s,d}} \leq \text{through}_{d} * \text{open}_{d}
\quad \forall d \in \text{Depots} - \text{Birmingham}
\end{equation}

- **Depot capacity (Birmingham)**: Flow into Birmingham must respect depot capacity, which may have been expanded.

\begin{equation}
\sum_{s \in \text{Cities}} \text{flow}_{s,\text{Birmingham}} \leq \text{through}_{\text{Birmingham}} + 20000 * \text{expand}
\end{equation}

- **Open depots**: At most 4 open depots (no choice for Birmingham or London).

\begin{equation}
\sum_{d \in \text{Depots}}{\text{open}_{d}} \leq 4
\end{equation}

\begin{equation}
\text{open}_{\text{Birmingham}} = \text{open}_{\text{London}} = 1
\end{equation}

---
### Python Implementation

We import the Gurobi Python Module and other Python libraries.

In [24]:
import copy
import pandas as pd
import matplotlib.pyplot as plt
import gurobipy as gp
from gurobipy import GRB

In [25]:
# Input Data
# Create dictionaries to capture factory supply limits, depot throughput limits, cost of opening depots, and customer demand.

supply = dict({'Liverpool': 150000,'Brighton': 200000})

through = dict({'Newcastle': 70000,
                'Birmingham': 50000,
                'London': 100000,
                'Exeter': 40000,
                'Bristol': 30000,
                'Northampton': 25000})

opencost = dict({'Newcastle': 10000,
                 'Birmingham': 0,
                 'London': 0,
                 'Exeter': 5000,
                 'Bristol': 12000,
                 'Northampton': 4000})

demand = dict({'C1': 50000,
               'C2': 10000,
               'C3': 40000,
               'C4': 35000,
               'C5': 60000,
               'C6': 20000})

# Create a dictionary to capture shipping costs.

arcs, cost = gp.multidict({
    ('Liverpool', 'Newcastle'): 0.5,
    ('Liverpool', 'Birmingham'): 0.5,
    ('Liverpool', 'London'): 1.0,
    ('Liverpool', 'Exeter'): 0.2,
    ('Liverpool', 'Bristol'): 0.6,
    ('Liverpool', 'Northampton'): 0.4,
    ('Liverpool', 'C1'): 1.0,
    ('Liverpool', 'C3'): 1.5,
    ('Liverpool', 'C4'): 2.0,
    ('Liverpool', 'C6'): 1.0,
    ('Brighton', 'Birmingham'): 0.3,
    ('Brighton', 'London'): 0.5,
    ('Brighton', 'Exeter'): 0.2,
    ('Brighton', 'Bristol'): 0.4,
    ('Brighton', 'Northampton'): 0.3,
    ('Brighton', 'C1'): 2.0,
    ('Newcastle', 'C2'): 1.5,
    ('Newcastle', 'C3'): 0.5,
    ('Newcastle', 'C5'): 1.5,
    ('Newcastle', 'C6'): 1.0,
    ('Birmingham', 'C1'): 1.0,
    ('Birmingham', 'C2'): 0.5,
    ('Birmingham', 'C3'): 0.5,
    ('Birmingham', 'C4'): 1.0,
    ('Birmingham', 'C5'): 0.5,
    ('London', 'C2'): 1.5,
    ('London', 'C3'): 2.0,
    ('London', 'C5'): 0.5,
    ('London', 'C6'): 1.5,
    ('Exeter', 'C3'): 0.2,
    ('Exeter', 'C4'): 1.5,
    ('Exeter', 'C5'): 0.5,
    ('Exeter', 'C6'): 1.5,
    ('Bristol', 'C1'): 1.2,
    ('Bristol', 'C2'): 0.6,
    ('Bristol', 'C3'): 0.5,
    ('Bristol', 'C5'): 0.3,
    ('Bristol', 'C6'): 0.8,
    ('Northampton', 'C2'): 0.4,
    ('Northampton', 'C4'): 0.5,
    ('Northampton', 'C5'): 0.6,
    ('Northampton', 'C6'): 0.9
})

#### Model Deployment
- The 'flow' variables simply capture the amount of product that flows along each allowed path between a source and destination.  
- The 'open' variable capture decisions about which depots to open.  
- The 'expand' variable captures the choice of whether to expand Birmingham.

In [26]:
model = gp.Model('SupplyNetworkDesign')
model.Params.LogToConsole = 0 # Suppresses repetitive Gurobi terminal output

depots = through.keys()
flow = model.addVars(arcs, obj=cost, name="flow")
open = model.addVars(depots, obj=opencost, vtype=GRB.BINARY, name="open")
expand = model.addVar(obj=3000, vtype=GRB.BINARY, name="expand")

open['Birmingham'].lb = 1
open['London'].lb = 1

# Base objective constant
model.objcon = -(opencost['Newcastle'] + opencost['Exeter'])

Set parameter LogToConsole to value 0

#### Production & Flow Constraints

In [27]:
factories = supply.keys()
customers = demand.keys()
all_but_birmingham = list(set(depots) - set(['Birmingham']))

# 1. Factory Production Limits
factory_flow = model.addConstrs((gp.quicksum(flow.select(factory, '*')) <= supply[factory]
                                 for factory in factories), name="factory")

# 2. Customer Demand (Saved as a variable to edit the RHS later)
customer_flow = model.addConstrs((gp.quicksum(flow.select('*', customer)) == demand[customer]
                                  for customer in customers), name="customer")

# 3. Flow Conservation at Depots
depot_flow = model.addConstrs((gp.quicksum(flow.select(depot, '*')) == gp.quicksum(flow.select('*', depot))
                               for depot in depots), name="depot")

# 4. Standard Depot Capacity Limits
depot_capacity = model.addConstrs((gp.quicksum(flow.select(depot, '*')) <= through[depot]*open[depot]
                                   for depot in all_but_birmingham), name="depot_capacity")

# 5. Birmingham Expansion Capacity Limit
birmingham_capacity = model.addConstr(gp.quicksum(flow.select('*', 'Birmingham')) <= through['Birmingham'] +
                                      20000*expand, name="birmingham_capacity")

# 6. Cardinality limit
depot_count = model.addConstr(open.sum() <= 4)

##### Baseline Optimization & Output

In [28]:
model.optimize()

print('--- Baseline Optimal Solution ---')
print(f"Total Objective Cost: ${model.ObjVal:,.2f}")
print('List of open depots:', [d for d in depots if open[d].x > 0.5])
if expand.x > 0.5:
    print('Action: Expand Birmingham capacity')

product_flow = pd.DataFrame(
    [{"From": arc[0], "To": arc[1], "Flow": flow[arc].x} for arc in arcs if flow[arc].x > 1e-6]
).sort_values("Flow", ascending=False)

product_flow.index=[''] * len(product_flow)
display(product_flow)

--- Baseline Optimal Solution ---
Total Objective Cost: $174,000.00
List of open depots: ['Birmingham', 'London', 'Exeter', 'Northampton']
Action: Expand Birmingham capacity

         From           To     Flow
     Brighton   Birmingham  70000.0
    Liverpool           C1  50000.0
   Birmingham           C5  50000.0
     Brighton       Exeter  40000.0
       Exeter           C3  40000.0
     Brighton  Northampton  25000.0
  Northampton           C4  25000.0
    Liverpool           C6  20000.0
     Brighton       London  10000.0
   Birmingham           C2  10000.0
   Birmingham           C4  10000.0
       London           C5  10000.0

---
#### Sensitivity Analysis Helpers (Fixed)

The product demand from all of our customers can be satisfied for a total cost of $\$174,000$ by opening a depot in Northampton, closing the depot in Newcastle, and expanding the depot in Birmingham:

In [29]:
# ---------- Sensitivity Helpers & Backups ----------
base_cost = copy.deepcopy(cost)
base_opencost = copy.deepcopy(opencost)
base_demand = copy.deepcopy(demand)

def set_explicit_objective():
    shipping_expr = gp.quicksum(base_cost[a] * flow[a] for a in arcs)
    open_expr = gp.quicksum(base_opencost[d] * open[d] for d in open.keys())
    expand_expr = 3000 * expand  
    
    # Mathematical correction applied: re-introducing the constant
    model.setObjective(shipping_expr + open_expr + expand_expr - 15000, GRB.MINIMIZE)
    model.update()

def print_solution_summary(prefix="", show_flows=False):
    if model.Status != GRB.OPTIMAL:
        print(f"{prefix} Model status: Infeasible or Unbounded")
        return
    opened = [d for d in open.keys() if open[d].X > 0.5]
    expand_dec = int(expand.X)
    print(f"{prefix} Objective: ${model.ObjVal:,.2f} | Open depots: {opened} | Expand(Birmingham): {expand_dec}")
    
    # Conditionally print the routing table
    if show_flows:
        print(f"{prefix} Top flows:")
        product_flow = pd.DataFrame(
            [{"src": arc[0], "dst": arc[1], "tons": flow[arc].x} for arc in arcs if flow[arc].x > 1e-6]
        ).sort_values("tons", ascending=False)
        display(product_flow)
        print("-" * 40)

##### Transport Cost Multiplier Sweep

In [30]:
# ---------- Sensitivity: Transportation Cost Multiplier ----------
print("--- Transport Cost Volatility ---")
multipliers = [0.9, 1.0, 1.1]   

for m in multipliers:
    for a in list(base_cost.keys()):
        base_cost[a] = cost[a] * m 
    set_explicit_objective()
    model.optimize()
    print_solution_summary(prefix=f"[Transport Cost x{m}]", show_flows=True)

# Restore base costs
for a in list(cost.keys()):
    base_cost[a] = cost[a]
set_explicit_objective()

--- Transport Cost Volatility ---
[Transport Cost x0.9] Objective: $156,300.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Transport Cost x0.9] Top flows:

            src          dst     tons
2      Brighton   Birmingham  70000.0
0     Liverpool           C1  50000.0
8    Birmingham           C5  50000.0
4      Brighton       Exeter  40000.0
10       Exeter           C3  40000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
1     Liverpool           C6  20000.0
3      Brighton       London  10000.0
6    Birmingham           C2  10000.0
7    Birmingham           C4  10000.0
9        London           C5  10000.0

----------------------------------------
[Transport Cost x1.0] Objective: $174,000.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Transport Cost x1.0] Top flows:

            src          dst     tons
2      Brighton   Birmingham  70000.0
0     Liverpool           C1  50000.0
8    Birmingham           C5  50000.0
4      Brighton       Exeter  40000.0
10       Exeter           C3  40000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
1     Liverpool           C6  20000.0
3      Brighton       London  10000.0
6    Birmingham           C2  10000.0
7    Birmingham           C4  10000.0
9        London           C5  10000.0

----------------------------------------
[Transport Cost x1.1] Objective: $191,700.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Transport Cost x1.1] Top flows:

            src          dst     tons
2      Brighton   Birmingham  70000.0
0     Liverpool           C1  50000.0
8    Birmingham           C5  50000.0
4      Brighton       Exeter  40000.0
10       Exeter           C3  40000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
1     Liverpool           C6  20000.0
3      Brighton       London  10000.0
6    Birmingham           C2  10000.0
7    Birmingham           C4  10000.0
9        London           C5  10000.0

----------------------------------------

#### Expansion Cost Sweep (Fixed)

In [31]:
# ---------- Sensitivity: Expansion Cost Sweep ----------
print("\n--- Facility Expansion Cost Thresholds ---")
expansion_costs = [2000, 3000, 4000, 5000, 8000]   

for ec in expansion_costs:
    shipping_expr = gp.quicksum(base_cost[a] * flow[a] for a in arcs)
    open_expr = gp.quicksum(base_opencost[d] * open[d] for d in open.keys())
    expand_expr = ec * expand
    
    # Mathematical correction applied
    model.setObjective(shipping_expr + open_expr + expand_expr - 15000, GRB.MINIMIZE)
    model.update()
    model.optimize()
    print_solution_summary(prefix=f"[Expand Cost ${ec}]", show_flows=True)
# Restore base objective
set_explicit_objective()

--- Facility Expansion Cost Thresholds ---
[Expand Cost $2000] Objective: $173,000.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Expand Cost $2000] Top flows:

            src          dst     tons
2      Brighton   Birmingham  70000.0
0     Liverpool           C1  50000.0
8    Birmingham           C5  50000.0
4      Brighton       Exeter  40000.0
10       Exeter           C3  40000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
1     Liverpool           C6  20000.0
3      Brighton       London  10000.0
6    Birmingham           C2  10000.0
7    Birmingham           C4  10000.0
9        London           C5  10000.0

----------------------------------------
[Expand Cost $3000] Objective: $174,000.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Expand Cost $3000] Top flows:

            src          dst     tons
2      Brighton   Birmingham  70000.0
0     Liverpool           C1  50000.0
8    Birmingham           C5  50000.0
4      Brighton       Exeter  40000.0
10       Exeter           C3  40000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
1     Liverpool           C6  20000.0
3      Brighton       London  10000.0
6    Birmingham           C2  10000.0
7    Birmingham           C4  10000.0
9        London           C5  10000.0

----------------------------------------
[Expand Cost $4000] Objective: $175,000.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Expand Cost $4000] Top flows:

            src          dst     tons
2      Brighton   Birmingham  70000.0
0     Liverpool           C1  50000.0
8    Birmingham           C5  50000.0
4      Brighton       Exeter  40000.0
10       Exeter           C3  40000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
1     Liverpool           C6  20000.0
3      Brighton       London  10000.0
6    Birmingham           C2  10000.0
7    Birmingham           C4  10000.0
9        London           C5  10000.0

----------------------------------------
[Expand Cost $5000] Objective: $175,000.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 0
[Expand Cost $5000] Top flows:

            src          dst     tons
1     Liverpool           C1  50000.0
3      Brighton   Birmingham  50000.0
0     Liverpool       Exeter  40000.0
10       Exeter           C3  40000.0
8    Birmingham           C5  30000.0
4      Brighton       London  30000.0
9        London           C5  30000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
2     Liverpool           C6  20000.0
7    Birmingham           C4  10000.0
6    Birmingham           C2  10000.0

----------------------------------------
[Expand Cost $8000] Objective: $175,000.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 0
[Expand Cost $8000] Top flows:

            src          dst     tons
0     Liverpool           C1  50000.0
2      Brighton   Birmingham  50000.0
10       Exeter           C3  40000.0
4      Brighton       Exeter  40000.0
8    Birmingham           C5  30000.0
3      Brighton       London  30000.0
9        London           C5  30000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
1     Liverpool           C6  20000.0
7    Birmingham           C4  10000.0
6    Birmingham           C2  10000.0

----------------------------------------

##### Demand Scaling (Fixed)

In [32]:
# ---------- Sensitivity: Demand Scaling ----------
print("\n--- Market Demand Contractions & Surges ---")
demand_factors = [0.8, 1.0, 1.2]   

for f in demand_factors:
    # Mathematical correction: Modifying the constraint limits dynamically
    for c in base_demand.keys():
        customer_flow[c].rhs = base_demand[c] * f
        
    model.optimize()
    print_solution_summary(prefix=f"[Demand x{f}]", show_flows=True)
# Restore original demand bounds
for c in base_demand.keys():
    customer_flow[c].rhs = base_demand[c]

--- Market Demand Contractions & Surges ---
[Demand x0.8] Objective: $130,900.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 0
[Demand x0.8] Top flows:

            src          dst     tons
2      Brighton   Birmingham  50000.0
0     Liverpool           C1  40000.0
4      Brighton       Exeter  40000.0
8    Birmingham           C5  39000.0
10       Exeter           C3  32000.0
12  Northampton           C4  25000.0
5      Brighton  Northampton  25000.0
1     Liverpool           C6  16000.0
11       Exeter           C5   8000.0
6    Birmingham           C2   8000.0
7    Birmingham           C4   3000.0
3      Brighton       London   1000.0
9        London           C5   1000.0

----------------------------------------
[Demand x1.0] Objective: $174,000.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Demand x1.0] Top flows:

            src          dst     tons
3      Brighton   Birmingham  70000.0
1     Liverpool           C1  50000.0
8    Birmingham           C5  50000.0
0     Liverpool       Exeter  40000.0
10       Exeter           C3  40000.0
5      Brighton  Northampton  25000.0
11  Northampton           C4  25000.0
2     Liverpool           C6  20000.0
7    Birmingham           C4  10000.0
6    Birmingham           C2  10000.0
4      Brighton       London  10000.0
9        London           C5  10000.0

----------------------------------------
[Demand x1.2] Objective: $220,500.00 | Open depots: ['Birmingham', 'London', 'Exeter', 'Northampton'] | Expand(Birmingham): 1
[Demand x1.2] Top flows:

            src          dst     tons
3      Brighton   Birmingham  70000.0
1     Liverpool           C1  60000.0
0     Liverpool       Exeter  40000.0
11       Exeter           C3  40000.0
4      Brighton       London  39000.0
10       London           C5  39000.0
9    Birmingham           C5  33000.0
12  Northampton           C4  25000.0
5      Brighton  Northampton  25000.0
2     Liverpool           C6  24000.0
8    Birmingham           C4  17000.0
6    Birmingham           C2  12000.0
7    Birmingham           C3   8000.0

----------------------------------------

---
### References
H. Paul Williams, Model Building in Mathematical Programming, fifth edition.